### ISSUE TITLE
When I filter by object key which can be equals null

### ISSUE THREAD

**Issue by studentIvan** [VadimDez/ng2-filter-pipe#15]
When I filter by object key which can be equals null - I see the error, because script trying to do null.toLowerString

The temporary solution is to replace all nulls to '' into your filtering data.

**Comment by VadimDez** [comment]
@studentIvan Could you explain the part `object key which can be equals null` ? Did you mean the `value` equals to null?

**Comment by studentIvan** [comment]
@VadimDez probably yes, I forget it at this moment. But the fix did work well.
