### ISSUE TITLE
LowerCase error.

### ISSUE THREAD

**Issue by Sevensnake** [VadimDez/ng2-filter-pipe#18]
`core.umd.js:2840 ORIGINAL EXCEPTION: value.toLowerCase is not a function
ErrorHandler.handleError @ core.umd.js:2840
next @ core.umd.js:6424
schedulerFn @ core.umd.js:5722
SafeSubscriber.__tryOrUnsub @ Subscriber.ts:238
SafeSubscriber.next @ Subscriber.ts:190
Subscriber._next @ Subscriber.ts:135
Subscriber.next @ Subscriber.ts:95
Subject.next @ Subject.ts:61
EventEmitter.emit @ core.umd.js:5714
NgZone.triggerError @ core.umd.js:6018
onHandleError @ core.umd.js:5997
ZoneDelegate.handleError @ zone.js:246
Zone.runGuarded @ zone.js:129
NgZone.runGuarded @ core.umd.js:5871
outsideHandler @ platform-browser.umd.js:1829
ZoneDelegate.invokeTask @ zone.js:275
Zone.runTask @ zone.js:151
ZoneTask.invoke @ zone.js:345
core.umd.js:2843 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ core.umd.js:2843
next @ core.umd.js:6424
schedulerFn @ core.umd.js:5722
SafeSubscriber.__tryOrUnsub @ Subscriber.ts:238
SafeSubscriber.next @ Subscriber.ts:190
Subscriber._next @ Subscriber.ts:135
Subscriber.next @ Subscriber.ts:95
Subject.next @ Subject.ts:61
EventEmitter.emit @ core.umd.js:5714
NgZone.triggerError @ core.umd.js:6018
onHandleError @ core.umd.js:5997
ZoneDelegate.handleError @ zone.js:246
Zone.runGuarded @ zone.js:129
NgZone.runGuarded @ core.umd.js:5871
outsideHandler @ platform-browser.umd.js:1829
ZoneDelegate.invokeTask @ zone.js:275
Zone.runTask @ zone.js:151
ZoneTask.invoke @ zone.js:345
core.umd.js:2844 TypeError: value.toLowerCase is not a function
    at eval (http://localhost:5192/node_modules/ng2-filter-pipe/dist/src/ng2-filter.pipe.js:12:37)
    at Array.filter (native)`

**Comment by VadimDez** [comment]
@Sevensnake need more info, please provide `array` that you are filtering and `filter` itself

**Comment by Sevensnake** [comment]
ok I did a simple one and it worked but maybe it is my data. take a look.
`[{"ID":2,"TeamID":4,"FirstName":"hrad","LastName":"erts","PhoneNumber":"211333","Mobile":"","EmailAddress":"","Address1":"","Address2":"","City":"","State":"GA","Zip":"","Name":"Rorts Brad"},{"ID":3,"TeamID":3,"FirstName":"David","LastName":"Delaney","PhoneNumber":"42611333","Mobile":"","EmailAddress":"","Address1":"","Address2":"","City":"","State":"GA","Zip":"","Name":"Delaney David"},{"ID":4,"TeamID":4,"FirstName":"Tim","LastName":"Dod","PhoneNumber":"401333","Mobile":"","EmailAddress":"","Address1":"","Address2":"","City":"","State":null,"Zip":"","Name":"Dod Tim"},{"ID":5,"TeamID":5,"FirstName":"David","LastName":"Greene","PhoneNumber":"40611333","Mobile":"","EmailAddress":"","Address1":"","Address2":"","City":"","State":"GA","Zip":"","Name":"Ge Dad"},{"RelationshipManagerID":6,"TeamID":5,"FirstName":"Cig Elliott","LastName":"Savage","PhoneNumber":"4011333","Mobile":"","EmailAddress":"","Address1":"","Address2":"","City":"","State":"GA","Zip":"","Name":"Savaig Elliott"},{"ID":7,"TeamID":5,"FirstName":"Shan","LastName":"Srivatsaa","PhoneNumber":"40333","Mobile":"","EmailAddress":"","Address1":"","Address2":"","City":"","State":"GA","Zip":"","Name":"Stsaa Sharan"},{"ID":8,"TeamID":5,"FirstName":"John","LastName":"Pitt","PhoneNumber":"4011333","Mobile":"","EmailAddress":"","Address1":"","Address2":"","City":"","State":"GA","Zip":"","Name":"Pitt John"},{"ID":9,"TeamID":6,"FirstName":"Robert","LastName":"Douglas","PhoneNumber":"4026133","Mobile":"","EmailAddress":"","Address1":"","Address2":"","City":"","State":"GA","Zip":"","Name":"Douglas Robert"},{"ID":11,"TeamID":8,"FirstName":"Troy","LastName":"Saldivar","PhoneNumber":"7135619300","Mobile":"","EmailAddress":"tsaldr@kany.com","Address1":"55n Felipe Road","Address2":"","City":"Houston","State":"TX","Zip":"772701","Name":"Saldivar Troy"},{"RelationshipManagerID":12,"TeamID":9,"FirstName":"James","LastName":"Shelton","PhoneNumber":"9995619300","Mobile":"","EmailAddress":"on@kanaly.com","Address1":"5555 San Felipe Blvd","Address2":"","City":"Houston","State":"TX","Zip":"77701","Name":"Sheltames"},{"ID":13,"TeamID":10,"FirstName":"x","LastName":"x","PhoneNumber":"3376921","Mobile":"","EmailAddress":"","Address1":"","Address2":"","City":"","State":null,"Zip":"","Name":"x x"},{"ID":15,"TeamID":12,"FirstName":"Tripps Moog","LastName":"Knch Kloberdanz","PhoneNumber":"403001","Mobile":"","EmailAddress":"krundanz@credsuissom","Address1":"","Address2":"","City":"","State":null,"Zip":"","Name":"Krudoog"},{"ID":16,"TeamID":13,"FirstName":"Alice","LastName":"Wu","PhoneNumber":"41492287","Mobile":"","EmailAddress":"","Address1":"","Address2":"","City":"San Francisco","State":"CA","Zip":"","Name":"ice"},{"ID":17,"TeamID":14,"FirstName":"Joel","LastName":"Shtt","PhoneNumber":"7h619345","Mobile":"","EmailAddress":"hcoanahom","Address1":"","Address2":"","City":"","State":null,"Zip":"","Name":"Scott Joel"},{"ID":18,"TeamID":15,"FirstName":"Corpening","LastName":"Group","PhoneNumber":"33646921","Mobile":"","EmailAddress":"","Address1":"","Address2":"","City":"","State":null,"Zip":"","Name":"Group Corpening"},{"ID":20,"TeamID":16,"FirstName":"John","LastName":"Desa","PhoneNumber":"27138364","Mobile":"","EmailAddress":"ddlavubs.com","Address1":"","Address2":"","City":"","State":null,"Zip":"","Name":"Ddsa John"},{"ID":21,"TeamID":17,"FirstName":"Kyle","LastName":"Zenner","PhoneNumber":"0000000000","Mobile":"","EmailAddress":"","Address1":"","Address2":"","City":"Houston","State":"TX","Zip":"","Name":"Zenner Kyle"},{"ID":22,"TeamID":18,"FirstName":"BrydSpaks","LastName":"Bdn/Spry/Zaks","PhoneNumber":"337246921","Mobile":"","EmailAddress":"","Address1":"","Address2":"","City":"","State":"CA","Zip":"","Name":"Badaks"}]
`

**Comment by Sevensnake** [comment]
I see a problem because I return object, object instead. Not sure how to correct this.

**Comment by Sevensnake** [comment]
Here is an example of what I am going through
[](http://stackoverflow.com/questions/39563243/angular-2-0-0-final-custom-pipe-filter-returns-object-object)

**Comment by Sevensnake** [comment]
http://stackoverflow.com/questions/39563243/angular-2-0-0-final-custom-pipe-filter-returns-object-object

**Comment by Sevensnake** [comment]
Never mind I figured it out. I was returning objects. So I had to do a Json parse and do a string replace to return the correct value.

**Comment by dearibujar** [comment]
Hey i got the same issue how did you figure it out? What do you mean with string replace and why did you json parse an object?
