### ISSUE TITLE
Filter a list of objects

### ISSUE THREAD

**Issue by davidtweaver** [VadimDez/ng2-filter-pipe#21]
Hello, suppose I have a list of objects in an *NgFor loop, and I want to filter by a property of one of those objects (e.g. the object is 'person' and it has a property 'name') - could I do that with this plugin? What about filtering by multiple properties?

**Comment by VadimDez** [comment]
@davidtweaver, Yes you can do that. That's exactly what this pipe supposed to do.

**Comment by davidtweaver** [comment]
But how do I do that? I'm fairly new to angular 2 - how does the pipe know which of the object's properties it's supposed to filter?

**Comment by VadimDez** [comment]
Here's some code from example,
[this is how you define list of objects and the filter for it](https://github.com/VadimDez/ng2-filter-pipe/blob/master/examples/ng-cli/src/app/app.component.ts#L31-L59)
and [this is how you use it in your template](https://github.com/VadimDez/ng2-filter-pipe/blob/master/examples/ng-cli/src/app/app.component.html#L87-L89).
Hope that helps

**Comment by davidtweaver** [comment]
Hello,  thank you for your help - I seem to be able to filter if I hardcode the value of objectFilter to something - but whenever I type in the input box I get "Error in ./ExportDataPage class ExportDataPage - caused by: value.toLowerCase is not a function" - am I missing a dependency or something? Do you have any idea what it might be?

Sorry for being such a n00b, and thank you so much for your time.

**Comment by VadimDez** [comment]
@davidtweaver I updated example in the readme file, https://github.com/VadimDez/ng2-filter-pipe/blob/master/README.md
Let me know if that helps
