### ISSUE TITLE
value.toLowerCase is not a function

### ISSUE THREAD

**Issue by dearibujar** [VadimDez/ng2-filter-pipe#28]
I try to use your pipe on a table , and i get this error value.toLowerCase is not a function

**Comment by VadimDez** [comment]
Could you provide more details? For example the data you are trying to filter.

**Comment by dearibujar** [comment]
I am using the filter on a array of objects, where each user is an object, there are nested objects in users.

**Comment by VadimDez** [comment]
okay, and what is your `filter` ?

**Comment by dearibujar** [comment]
Oops :S it is a string . How should i use it then on an objec? I am new to angular2 sorry.

**Comment by VadimDez** [comment]
You need to make the filter similar to the object you want to filter. For example you want to filter users by their name:
```ts
users: any[] = [{ name: 'John' }, { name: 'Jane' }, { name: 'Mario' }];
```

then your filter would be:

```ts
userFilter: any = { name: '' };
```

**Comment by dearibujar** [comment]
Even with object i get the same error. Could you describe it a little better how it should be used. With an example where there are used more fields in *ngFor not just name, and using a table where users are shown in rows?

**Comment by VadimDez** [comment]
That would be the same for more fields in the object
```ts
users: any[] = [{ name: 'John', age: 25 }, { name: 'Jane', age: 26 }, { name: 'Mario', age: 25 }];
```

```ts
userFilter: any = { name: '', age: null };
```

**Comment by dearibujar** [comment]
Does that mean that i have to include in the filter object all the user object properies and set them to null? However thank you for helping

**Comment by VadimDez** [comment]
No, what i wanted to say is - you just need to add fields that you want your array of objects to be filtered by. In that case i did an example when i would filter by `name` AND `age`. If you have more fields or nested fields you would add once that you want to filter by, just match the structure of your objects.

**Comment by dearibujar** [comment]
No luck yet, here is my filter object  `userFilter:any={name :''};` and i still get **EXCEPTION: Error in ./UsersComponent class UsersComponent - inline template:26:19 caused by: Cannot read property 'toLowerCase' of undefined**

**Comment by VadimDez** [comment]
@dearibujar did you try to put `users` and `userFilter` from my example ?
Otherwise, show me your data (make a mock of sensitive data if you want...) and html where you're using `filterBy`.

**Comment by dearibujar** [comment]
@VadimDez  I tried with your sample data also, same error. I will provide you also with  a mock of my data and the html. But is it maybe the latest angular version that is causing the problem?  By the way , i am using  angular/cli

**Comment by dearibujar** [comment]
I deleted your pipe and installed it from the begining, now it is working. But thank you for taking time, have a nice day.

**Comment by alexsalmon** [comment]
This issue is present in the [examples](https://vadimdez.github.io/ng2-filter-pipe/), on the first "object.num" input.
