### ISSUE TITLE
Filter fails when filter value is zero

### ISSUE THREAD

**Issue by SaraYoussef** [VadimDez/ng2-filter-pipe#32]
In the code you check if there is no filter sent by `!filter` when the filter is number with value 0, the code assumes that there is no filter.

Solution:
use `filter === undefined` instead.

**Comment by shareefmoaryur** [comment]
fixed this issue by replacing the following code (ng2-filter.pipe.js:66)

Ng2FilterPipe.prototype.filterDefault = function(filter) {
        return function(value) {
            return filter === undefined || filter == value;
        };
    };
