### ISSUE TITLE
Add $or operator

### ISSUE THREAD

**Issue by VadimDez** [VadimDez/ng2-filter-pipe#4]
$or operator would allow OR conditions

**Comment by ajkyru** [comment]
Now is there any way to search for multiple fields using one input field? For example: search by the name of an automobile part or its name, using only one input field.

**Comment by VadimDez** [comment]
@ajkyru not yet implemented, but will be

**Comment by VadimDez** [comment]
@ajkyru temporary solution could be to expose a `getter` function that returns value of both fields and then filter by that value. You can find an example at the end of the demo page https://vadimdez.github.io/ng2-filter-pipe
