### ISSUE TITLE
ObjectFiltering

### ISSUE THREAD

**Issue by timteka** [VadimDez/ng2-filter-pipe#5]
Vadim, could you please show us how to use ng2-filter-pipe for object filtering.
Say [{'surname':'reeves', 'firstname':'keanu'}] filter by firstname?

**Comment by VadimDez** [comment]
Hi, @timteka, that would be something like this
```js
<ul>
  <li *ngIf="let user of [{'surname':'reeves', 'firstname':'keanu'}] | filterBy: {firstname: 'name'}">{{ user.firstname }}</li>
</ul>
```
Also you can find it here
https://github.com/VadimDez/ng2-filter-pipe/blob/master/src/app/ng2-filter-pipe.component.html#L50

**Comment by timteka** [comment]
I've tried it already, still no success:
```
ORIGINAL EXCEPTION: TypeError: Cannot read property 'filter' of undefined
ORIGINAL STACKTRACE:
TypeError: Cannot read property 'filter' of undefined
    at t.transform (http://10.10.10.10:3000/node_modules/ng2-filter-pipe/ng2-filter.pipe.min.js:1:1319)
```

**Comment by timteka** [comment]
Angular 2 rc5.
Seems like it is my mistake. i didn't mention that i operate with array of objects. Here's the code fragment:
```
<div class="row user" *ngFor="let pbxuser of pbxusers | filterBy: {ext:'0105'}">
                
                    <div class="col-md-5 col-sm-5">{{pbxuser.dept}}</div>
                    <div class="col-md-6 col-sm-6">{{pbxuser.fio}}</div>
                    <div class="col-md-1 col-sm-1">{{pbxuser.ext}}</div>
            </div>
```

**Comment by VadimDez** [comment]
@timteka, by passing array to FilterBy you want to filter them something like inArray ? Did i get you right?

**Comment by timteka** [comment]
Sorry for bothering you, Vadim, need some time to learn more Angular :-) Seems like i'm passing empty Array initially to your filter (getting data later via http.get service).

**Comment by timteka** [comment]
Vadim, thanks a lot! It's working now! I've inited the [pbxusers] array and not your filter is definitely filtering! :+1:
