### ISSUE TITLE
if array is a object of Array type, it can't work

### ISSUE THREAD

**Issue by lzm420241** [VadimDez/ng2-filter-pipe#8]

**Comment by VadimDez** [comment]
@lzm420241, could you show me example of the object?

**Comment by lzm420241** [comment]
@VadimDez  my ex array like this:
`[
[{ id: 1, 
  name: "fkds", 
  sub:[
   {id:1,name: "dks"}
 ]}
]`

**Comment by lzm420241** [comment]
`<li *ngFor="let item of coffeeDetailInfoList | filterBy: stringFilter ">
					<div *ngIf = " (item.subGroups.length != 0 || item.subMachines.length != 0 ) && (item.selectStatus != 1) "><span class="icon" (click) = "changeStatus( item )" [class.active] = "item.selected != 0" ></span><span class="name">{{item.name}}</span><span class="move" (click)="moveRightItem( 1, item, 0, 0 )">+</span></div>
					<ul *ngIf = " item.subGroups && item.selected != 0 ">
						<li *ngFor= " let group of item.subGroups " [class.hide] = "group.selectStatus == 1" ><div><span class="icon" (click) = "changeStatus( group )" [class.active] = "group.selected != 0" ></span><span class="name">{{ group.groupName }}</span><span class="move" (click)="moveRightItem( 3, item, group, 0 )">+</span></div>
						  <ul *ngIf=" group.subMachines && group.selected != 0 ">  
						    <li *ngFor="let machineInfo of group.subMachines " [class.hide] = "machineInfo.selectStatus == 1" ><div><span class="name">{{ machineInfo.machineName }}-{{ machineInfo.address }}</span><span class="move" (click)="moveRightItem( 4, item, group, machineInfo )">+</span></div></li>  
						  </ul>  
						</li> 
						<li *ngFor="let machines of item.subMachines " class="show-location" [class.hide] = " machines.selectStatus == 1">
							<div><span class="name">{{ machines.machineName }}-{{ machines.address }}</span><span class="move" (click)="moveRightItem( 2, item, machines, 0 )">+</span></div>
						</li> 
					</ul>`

**Comment by VadimDez** [comment]
You can't filter object with just a string, you need to make `stringFilter` object as well, and if you want to filter by `name` - you have to make:
```js
stringFIlter = { name: '' }
```
and in your html instead of `[(ngModel)]="stringFilter"` do `[(ngModel)]="stringFilter.name"`

**Comment by lzm420241** [comment]
@VadimDez  thx, it solved problem,but if my html is 
<label>key:</label><input type="text" [(ngModel)]="stringFilter" >
<li *ngFor="let item of List | filterBy: stringFilter ">
<span>{{ item.name }}</span>
<ul *ngIf =" item.sub ">
  <li *ngFor = " let value of item.sub | filterBy: stringFilter">{{ value.name}}<li>
</ul>
</li>

when i search  sub :[name : "dks"], then because of item.name != search.value ,then the it can't show the child of li, i didn't find the API about mutiple condition for ng2=filter

**Comment by VadimDez** [comment]
Not sure, but maybe something like this ?

```html
<label>key:</label>
<input type="text" [(ngModel)]="stringFilter" >
<li *ngFor="let item of List" *ngIf="(item.sub | filterBy: stringFilter).length">
  <span>{{ item.name }}</span>
  <ul *ngIf =" item.sub ">
    <li *ngFor = " let value of item.sub | filterBy: stringFilter">{{ value.name}}<li>
  </ul>
</li>
```

**Comment by lzm420241** [comment]
@VadimDez  *ngFor and *ngIf can't use together!and  by this way, it only search for sub :[name : "dks"],right?

**Comment by cgowez** [comment]
Hi @VadimDez , first thanks for this package, it's great, however I would like to use it filtering multiple values, can you help me on how to use it? this is what I tried:

```
private stringFilter = { name: '', position: '', city: '' };

<input type="text" [(ngModel)]="stringFilter">
<ul *ngIf="peopleList">
    <li *ngFor="let item of peopleList | filterBy: stringFilter">
        {{item.name}}, {{item.position}}, {{item.city}}
    </li>
</ul>
```

I want to filter by name, position or city and I don't know how to specify this.
If I set [(ngModel)]="stringFilter.name" it works just for name, how can I cover for the other values?
Thanks for your help.

**Comment by VadimDez** [comment]
@cgowez, you can try to create one input field for each field in your filter.
Something like this:
```html
<input type="text" [(ngModel)]="stringFilter.name" name="name" placeholder="Name">
<input type="text" [(ngModel)]="stringFilter.position" name="position" placeholder="Position">
<input type="text" [(ngModel)]="stringFilter.city" name="city" placeholder="City">
```

**Comment by cgowez** [comment]
I thought on that however I don't think it's the best approach for user friendly, I'm thinking to create a new string with those three values, thanks for your quick response.

**Comment by cgowez** [comment]
hey @VadimDez this is what I did and worked as expected:
I added another value on the JSON response with the other values combined.

```
.json:
"together": "name position city',

.ts:
private stringFilter = { together: ''};

.html:
<label>Filter: </label><input type="text" [(ngModel)]="stringFilter.together">

<ul *ngIf="peopleList">
    <li *ngFor="let item of peopleList | filterBy: stringFilter">
        {{item.name}}, {{item.position}}, {{item.city}}
        <div style="display: none">{{item.together}}</div>
    </li>
</ul>
```

It works great, thanks.
