### ISSUE TITLE
is the package.json correct?

### ISSUE THREAD

**Issue by kodiraj** [VadimDez/ng2-filter-pipe#9]
the npm pull shows "its using angular rc6" but package.json shows different?

**Comment by VadimDez** [comment]
@kodiraj, if you delete `ng2-filter-pipe` package from `node_modules` and reinstall, do you get same error ?

**Comment by kodiraj** [comment]
moreover can you update the usage as well in the dcouementation.

Its not recognising the following syntax in componenets

 pipes: [Ng2FilterPipe],

**Comment by kodiraj** [comment]
to answer your question, even after doing it,its still pointing to the old rc6 version only
<img width="787" alt="screen shot 2016-11-24 at 5 01 56 pm" src="https://cloud.githubusercontent.com/assets/11332035/20597095/c1252a74-b267-11e6-9793-7347c1bbe2f7.png">

**Comment by kodiraj** [comment]
hi,

Any plan on when 0.0.5 would be available?

**Comment by VadimDez** [comment]
@kodiraj, i'll try to do it as soon as i can. Let's say this weekend.

**Comment by kodiraj** [comment]
Thanks
